### ISSUE TITLE
防災グッズチェックリスト

### ISSUE THREAD

**Issue by Akihi-Sumi** [Akihi-Sumi/GraduateProject#16]
担当者：高以良くん
### ToDo
- [ ] ユーザー作成と同時に、AppUsersコレクションに「SurvivalKit」コレクションが生成される
- [ ] チェックを入れると、「isChecked」が`true`になる
- [ ] 数値か日付など何らかのフィールド値を持たせ、時間経過後に「isChecked」を`false`にする

進捗状況・不明点などあれば返信してください。

**Comment by Akihi-Sumi** [comment]
Complete.
