### ISSUE TITLE
メッセージ･ウィジェット実装

### ISSUE THREAD

**Issue by Akihi-Sumi** [Akihi-Sumi/GraduateProject#17]
担当者：墨
### ToDo
- [x] Messageモデルに`isSender`ラベルを作り、messageBubbleの`isSender`と関連づける
- [x] ウィジェットの横に、送信時刻を表示する。変換の必要あり。
`sendedAt`ラベルが要る?　もしくはgroupMessageを流用して`createdAt`を更新する?
- [x] `isSender`で送信側と相手側の色を変えるのもアリ
- [x] AppUsers-Message → groupMessages に送信する処理

**Comment by Akihi-Sumi** [comment]
Finish this issue. Thank you.
